### ISSUE TITLE
Imports not resolving correctly

### ISSUE THREAD

**Issue by karatechops** [grommet/next-sample#3]
My branch for Grommet is on NEXT.
```
[grommet:pack]: Running webpack...
Using alias to local grommet.
[grommet:pack]: Starting dev server...
[grommet:pack]: failed
Module not found: Error: Can't resolve 'grommet/es6/components/grommet/Grommet' in '/Users/alexmejias/Projects/Work/HP/dev/grommet-NEXT/next-sample/src/js'
Module not found: Error: Can't resolve 'grommet/es6/components/button/Button' in '/Users/alexmejias/Projects/Work/HP/dev/grommet-NEXT/next-sample/src/js'
```

If I set my import to something more explicit like `import Grommet from 'grommet/components/grommet';` it works fine.

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/babel-plugin-grommet/commit/07df0ef1502484039758d0749aa4050ce420e768.

Make sure to update your node_modules and use babel-plugin-grommet version 0.2.1
